PLAT-43859: Fix Text is cropped in data grid list on iOS
enyojs/enyo-strawman pull request #363
Opened 2017-08-11 10:55 UTC by sriramas

### Issue Resolved / Feature Added
 Fix Text is cropped in data grid list when itemtype is Horizontal item/imageItem.

### Resolution
Changed the `top` from 18% to 5px.

### Additional Considerations

### Links
PLAT-43859

### Comments
Enyo-DCO-1.1-Signed-off-by: Srirama Singeri(srirama.singeri@lge.com)

2017-08-14 08:06 UTC, anishlg commented
LGTM

2017-08-24 16:43 UTC, aarontam requested changes
In general the change seems fairly innocuous and affects just this sample. It resolves the display issue on the affected device and the text still appears to be positioned well enough for other devices.

Just a minor comment in the PR to fix up.

2017-08-24 16:43 UTC, aarontam commented on src/moonstone-samples/lib/DataGridListSample.less
> +			top: 5px;
Let's use a multiple of 3 here i.e. `6px`

2017-08-28 16:55 UTC, aarontam approved these changes
:shipit:

2017-08-28 16:55 UTC, merged